version: '3.1'
services:
  gorpc_db:
    container_name: gorpc_db
    image: postgres:15.2
    ports:
      - 5445:5432
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  # volumes:
  #   postgres_data: